error out of staging refresh if aws-cli is not installed (#1049)
No sense in continuing the script without it and will save time when people (like me) don't have it and then end up with an empty staging database.

diff --git a/bin/copy_production_db_to_staging b/bin/copy_production_db_to_staging
--- a/bin/copy_production_db_to_staging
+++ b/bin/copy_production_db_to_staging
@@ -1,13 +1,20 @@
 #!/bin/sh
 
 # Requirements
-# - aws-cli
+# - aws-cli (brew install awscli)
 # - AWS environment variables
 #   * AWS_ACCESS_KEY_ID
 #   * AWS_SECRET_ACCESS_KEY
 #   * AWS_DEFAULT_REGION
+# - Metabase environment variables
+#   * METABASE_URL
 
 app='code-fund-ads-staging'
+
+if [ -z "$(which aws)" ]; then
+  echo 'aws-cli not installed! Aborting.';
+  exit 1
+fi
 
 ./bin/heroku_pg_dump_production_replica
 heroku pg:reset DATABASE_URL -a $app
